import './globals.css'
import WagmiRainbowKitProvider from './provider'
import '@rainbow-me/rainbowkit/styles.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <WagmiRainbowKitProvider>
          {children}
        </WagmiRainbowKitProvider>
      </body>
    </html>
  )
}
